CREATE TABLE films (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR (50) UNIQUE NOT NULL,
    pic_url VARCHAR (100) NOT NULL,
    desc_path VARCHAR (100) NOT NULL,
    film_path VARCHAR (100) NOT NULL,
    hash INT UNIQUE NOT NULL,
    rating INT DEFAULT -1,
    trailer_path VARCHAR (100) NOT NULL,
    added TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);